const baseUrl = process.env.REACT_APP_API_URL
export const signUpApiUrl = `${baseUrl}/api/users/signUp`
export const getUserListAPiUrl = `${baseUrl}/api/users`
export const signInApiUrl = `${baseUrl}/api/auth/signIn`
export const getFriendsApiUrl = `${baseUrl}/api/friends`
export const addTripApiUrl = `${baseUrl}/api/trips/addTrip`
export const getTripListApiUrl = `${baseUrl}/api/trips`
export const addExpenseApiUrl = `${baseUrl}/api/expenses/addExpense`
export const updateFriend = `${baseUrl}/api/users/addFriend`
export const completeTripApiUrl = `${baseUrl}/api/trips/completeTrip`
